In [21]:
import bqplot
import numpy as np

In [22]:
x = np.arange(100)

In [23]:
y = np.random.random(100)

In [24]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [25]:
lines = bqplot.Lines(x=x, y=y, scales = {'x':x_sc, 'y':y_sc})

In [26]:
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [27]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y])

In [28]:
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [29]:
pz = bqplot.interacts.PanZoom( scales = {'x': [x_sc], 'y': [y_sc]})

In [30]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=pz)

In [31]:
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [32]:
x = np.random.random(100)

In [33]:
x

array([0.64915764, 0.58861931, 0.80721005, 0.59858967, 0.88150102,
       0.05573093, 0.40938268, 0.09986777, 0.47003341, 0.31889156,
       0.39600366, 0.03820114, 0.43900977, 0.31474222, 0.12746307,
       0.5812921 , 0.12420179, 0.23680206, 0.35251306, 0.47775712,
       0.43917426, 0.08597837, 0.44582881, 0.58181299, 0.5960199 ,
       0.66885733, 0.35636068, 0.65855941, 0.86894269, 0.42189331,
       0.82362638, 0.4460666 , 0.52664357, 0.12323539, 0.10546151,
       0.679029  , 0.46669433, 0.10665849, 0.55897968, 0.74688844,
       0.63996218, 0.84161208, 0.98977864, 0.93763009, 0.54175833,
       0.32820297, 0.06521527, 0.82037897, 0.49296205, 0.89858844,
       0.69807978, 0.29903848, 0.16841181, 0.56921097, 0.8503008 ,
       0.68602965, 0.76427473, 0.27818424, 0.80651099, 0.74519357,
       0.52057056, 0.01829636, 0.88722767, 0.7884213 , 0.08306274,
       0.77072898, 0.59847094, 0.68933319, 0.92311241, 0.94240573,
       0.21787467, 0.59857132, 0.7527694 , 0.4948954 , 0.15550

In [34]:
y = np.random.random(100)

In [35]:
y

array([0.33603547, 0.77602696, 0.91815771, 0.05801819, 0.00515594,
       0.42313297, 0.76768728, 0.44233221, 0.45198008, 0.23294233,
       0.17236195, 0.78575535, 0.8523955 , 0.66541639, 0.1643369 ,
       0.59772788, 0.54062404, 0.02185447, 0.25937275, 0.50092689,
       0.10820443, 0.0385018 , 0.49533483, 0.84163663, 0.82206546,
       0.35729003, 0.55938664, 0.28793635, 0.37591898, 0.20926441,
       0.00988055, 0.18557558, 0.01273503, 0.7555732 , 0.25451069,
       0.76353115, 0.42534841, 0.6090838 , 0.54463068, 0.1776855 ,
       0.35364312, 0.9897529 , 0.24945146, 0.65754981, 0.36524841,
       0.1193943 , 0.69404782, 0.07631068, 0.81198727, 0.52665314,
       0.62132173, 0.96975553, 0.16267556, 0.29988104, 0.23197074,
       0.84704782, 0.87208152, 0.19344443, 0.156513  , 0.77193249,
       0.53310487, 0.36646415, 0.03853696, 0.10516111, 0.91799614,
       0.81560178, 0.21856731, 0.64220606, 0.77756782, 0.69514162,
       0.54166421, 0.2241872 , 0.57932841, 0.71306296, 0.16430

In [36]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [37]:
ax_x = bqplot.Axis(scale = x_sc, label="X")
ax_y = bqplot.Axis(scale = y_sc, label="Y", orientation='vertical')

In [38]:
scatters = bqplot.Scatter(x = x, y = y, scales={'x':x_sc, 'y':y_sc})

In [39]:
bqplot.Scatter

bqplot.marks.Scatter

In [40]:
bqplot.interacts.FastIntervalSelector

bqplot.interacts.FastIntervalSelector

In [41]:
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [42]:
fig = bqplot.Figure(marks=[scatters], axes=[ax_x, ax_y], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [43]:
selector.selected

In [44]:
scatters.unselected_style = {'opacity':0.8} # a little see-through when not selected
scatters.selected_style={'fill':'red', 'stroke':'yellow'}

In [45]:
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [46]:
x

array([0.64915764, 0.58861931, 0.80721005, 0.59858967, 0.88150102,
       0.05573093, 0.40938268, 0.09986777, 0.47003341, 0.31889156,
       0.39600366, 0.03820114, 0.43900977, 0.31474222, 0.12746307,
       0.5812921 , 0.12420179, 0.23680206, 0.35251306, 0.47775712,
       0.43917426, 0.08597837, 0.44582881, 0.58181299, 0.5960199 ,
       0.66885733, 0.35636068, 0.65855941, 0.86894269, 0.42189331,
       0.82362638, 0.4460666 , 0.52664357, 0.12323539, 0.10546151,
       0.679029  , 0.46669433, 0.10665849, 0.55897968, 0.74688844,
       0.63996218, 0.84161208, 0.98977864, 0.93763009, 0.54175833,
       0.32820297, 0.06521527, 0.82037897, 0.49296205, 0.89858844,
       0.69807978, 0.29903848, 0.16841181, 0.56921097, 0.8503008 ,
       0.68602965, 0.76427473, 0.27818424, 0.80651099, 0.74519357,
       0.52057056, 0.01829636, 0.88722767, 0.7884213 , 0.08306274,
       0.77072898, 0.59847094, 0.68933319, 0.92311241, 0.94240573,
       0.21787467, 0.59857132, 0.7527694 , 0.4948954 , 0.15550

In [47]:
y

array([0.33603547, 0.77602696, 0.91815771, 0.05801819, 0.00515594,
       0.42313297, 0.76768728, 0.44233221, 0.45198008, 0.23294233,
       0.17236195, 0.78575535, 0.8523955 , 0.66541639, 0.1643369 ,
       0.59772788, 0.54062404, 0.02185447, 0.25937275, 0.50092689,
       0.10820443, 0.0385018 , 0.49533483, 0.84163663, 0.82206546,
       0.35729003, 0.55938664, 0.28793635, 0.37591898, 0.20926441,
       0.00988055, 0.18557558, 0.01273503, 0.7555732 , 0.25451069,
       0.76353115, 0.42534841, 0.6090838 , 0.54463068, 0.1776855 ,
       0.35364312, 0.9897529 , 0.24945146, 0.65754981, 0.36524841,
       0.1193943 , 0.69404782, 0.07631068, 0.81198727, 0.52665314,
       0.62132173, 0.96975553, 0.16267556, 0.29988104, 0.23197074,
       0.84704782, 0.87208152, 0.19344443, 0.156513  , 0.77193249,
       0.53310487, 0.36646415, 0.03853696, 0.10516111, 0.91799614,
       0.81560178, 0.21856731, 0.64220606, 0.77756782, 0.69514162,
       0.54166421, 0.2241872 , 0.57932841, 0.71306296, 0.16430

In [ ]:
y.shape